### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by alis313** [vfarid/v2ray-worker-sub#1]
سلام
بابت کدخیلی خوبت ممنون
لطفا چند قابیلیت هم که به نظرم میاد بهش اضافه کنید بد نیست
1. قابلیت استفاده در نرم افزار کلش
2. در کد زیر اقای نصیری یه بخش به نام fallback اضافه کرده که بسیار کاربردی هست در نرم افزار کلش
[https://gist.github.com/nasiriscript/9b3997a49f85ac1090eef40be2699927](url)
3. این ساب رو هم اضافه کنید بد نیست 
 "https://raw.githubusercontent.com/vpei/Free-Node-Merge/main/o/node.txt"

**Comment by vfarid** [comment]
در مورد ۱ و ۲ اگه میتونید اصلاح کنید و pull بزنید بررسی می کنم. خودم هم فرصت کنم اوکی میکنم.
مورد ۳ رو اضافه کردم. متشکرم.
