### ISSUE TITLE
ورکر کد برای vless or trojan

### ISSUE THREAD

**Issue by hojatkh** [vfarid/v2ray-worker-sub#10]
سلام آقا فرید . من چندین بار این روش را امتحان کردم جواب نمیگیرم .در واقع هیچکدام از پروکسی های vmess روی سیستم من جواب نمیده . چه اینهایی که به روش شما میسازم چه اونایی که از جاهای دیگه میگیرم . اینترنتم adsl مخابراته .       
پرسش : آیا کدی هست که توی ورکر کلودفلر vless یا trojan بسازه ؟ چون این 2 مدل روی سیستم من خیلی خوب کار  می کنند.
 سپاسگذارم ......... حجت

**Comment by vfarid** [comment]
تو نسخه‌ی جدید (۱.۵) کانفیگ تروجان و vless هم پشتیبانی میشه
