### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by frezahc** [vfarid/v2ray-worker-sub#11]
با راه حل جدیدی که برای آیپی های کلادفلر معروف شده، امکانش هست بشه بعد آیپی پورت رو هم انتخاب کرد؟
مثلا
/sub/ip:port

**Comment by vfarid** [comment]
پورت رو کانفیک مشخص میکنه. نمیشه روی ساب، پورت بدیم. بی معنیه.

**Comment by vfarid** [comment]
براش یه فکری می کنم. این کار رو هم میشه کرد.
