### ISSUE TITLE
CPU time limite

### ISSUE THREAD

**Issue by MeiisamMahmoodii** [vfarid/v2ray-worker-sub#12]
وقتی درخواست SUB به ورکر فرستاده میشه توی کنسول این ارور های رو میده
Error: Worker exceeded CPU time limit.
8Uncaught (in response) Error: Worker exceeded CPU time limit.
و ارور 503 میده

**Comment by vfarid** [comment]
توی کنسول محدودیت زمانی برای اجرای کد داره. ذخیره کنید و لینک ورور رو تو بروزر بزنید برای تست.
