### ISSUE TITLE
تعداد کانفیگ

### ISSUE THREAD

**Issue by RealDevMrz** [vfarid/v2ray-worker-sub#13]
سلام خسته نباشید
وقتی از max استفاده میکنم روی mci و mkh و ... کار نمیکنه
برای مثال من از لینک
https://xxx.xxx.workers.dev/sub/mci?max=400
برای سابسکریپشن استفاده کردم و به من بیشتر از 800 تا کانفیگ داده.
ولی وقتی از لینک
https://xxx.xxx.workers.dev/sub/1.2.3.4?max=400
استفاده میکنم تعداد درسته، لطفا بررسی کنید🙏

**Comment by vfarid** [comment]
نه اشتباه می کنید تفاوتی نداره. وقتی max=400 میزنید در واقع ۴۰۰ تا ترکیب شده با ورکر به شما میده و ۴۰۰ تا هم کانفیگ اصلی.
برای اینکه دقیقا ۴۰۰ تا بگیرید یا تعداد رو نصف بدی یا کانفیگ های اصلی رو غیر فعال کنید:

https://xxx.xxx.workers.dev/sub/mci?max=400&original=0
https://xxx.xxx.workers.dev/sub/mci?max=200
