### ISSUE TITLE
trojan configs have no path

### ISSUE THREAD

**Issue by Mosiu9** [vfarid/v2ray-worker-sub#14]
سلام خسته نباشید من کد شمارو بدون هیچ تغییری اضافه کردم به ورکر اما کانفیگ های Trojan هیچگونه path ندارن و پینگ نمیدن
ممنون میشم بررسی کنید

و اینکه کانفیگ های vless هم اضافه نشد

**Comment by vfarid** [comment]
مشکل vless اینه که matsuri ازش پشتیبانی نمیکنه. تروجان‌ها بعضا کار می کنن. کلا مشکل اینه که من سورس خوبی از تروجان ندارم و تعدادشون خیلی کمه. سالم توشون پیدا نمیشه.
