### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by PikachuJP** [vfarid/v2ray-worker-sub#15]
درود مشکلات جدید ترین سورسی که دادی ایناست
اول اینکه برخلاف TOS های ورنگلر و کلادفلیر و سی پی یو تایم بالای پنجاه میلی ثانیه میخواد برای پردازش و دیپلوی کد که اگه ناپدید گرفته بشه بعد آپدیت های متوالی یا ورکرت رو میبندن یا حسابت بن میشه
دو تروجان و وی لس کاملا مزخرفه و به هیچ وجه وقتی میندازی پشت کلادفلیر جواب نمیده پس بهتره از سورس حذف بشه به کوتاهی و سبک بودن موافق قوانین کلادفلیر و ورنگلر نزدیک میشه
سه پورت هایی به غیر 443 کاملا بیخوده اونها هم من خودم مدت هاست این آپشن رو برای سورس خودم زده بودم پشت کلادفلیر اصلا جواب نمیده و دیدم پورت 2093 هم داخلشون هست که توی لیست ساپورت HTTPS کلادفلیر نیست اصلا
چهار کانفیگ هایی که از تی سی پی و جی پی آر سی هم دقیقا عین پرت های اضافی پشت کلادفلیر هیچ ارزشی نداره و کار نمیکنه صرفا شلوغی سرور ها و تایم اوت های بیشتر
پنج تعداد ریکوئست ها بعد سه چهار بار آپدیت ده درصد روزانه رو پر میکنه میشه با مکس ته لینک ساب محدود کرد ولی سورس باز هم اونهمه سرور رو فچ میکنه لود شدیدی میاره که بازم همون برخلاف قوانین استفاده از سرویسه تقریبا دوازده کی ریکوئست بعد چهار بار آپدیت پر شد

بنظرم سورس عالیه اما نیاز به سنگین کردنش نیست اصلا و اینکه توی لیست سرور ها که میاد تست که میگیری اکثرا همون سرور های فرینود هستن که ملت گرفتن اد زدن توی لیست سرورها توی گیت‌هاب کار میکنن، خب چکار میشه کرد؟ هیچی من خودم فقط همون فرینود هارو انداختم پشتش مثل جت کار میکنن سرور شخصی خودمم هست علاوه بر اون اما فرینود عالی کار میکنه لازم نیست از بخش برای ایران اکانت بگیرین همون اکانت عادی سرور هاشو میندازی پست کلادفلیر

پیشنهادم اینه بجای سنگین کردن سورس فقط روی آیپی تمیز کار میشد و سروری که مطمئنن سالمه مثل فرینود که بینشون هست و همونا کار میکنه به غیر VMESS هم چیزی پشت کلادفلیر جواب نمیده

**Comment by vfarid** [comment]
۱. کد من مشکلی برای اجرا روی ورکر نداره و شامل محدودیت نمیشه. ضمن اینکه دلیلی نداره شما پشت سر هم بخواید sub رو اجرا کنید. یه بار میزنید چند روز استفاده می کنید.
۲. تروجان و vless با ورکر کار میکنن. مساله اینه که ماسوری درست پشتیبانی نمیکنه و البته کانیگ خوب هم زیاد براشون نیست.
۳. تمام پورتها با ورکر کار میکنن و ورکر شامل محدودیت پورتهای آزاد کلادفلر نمیشه. اون محدودیت مربوط به cdn هستش.
۴. کانفیگ tcp که خیلی عالی کار میکنه. gprc هم روی http2 تبادل میشه و کاملا با ورکر سازگاره.
۵.  اینطور نیست

حالا من اینهمه نشستم خوندم و پاسخ دادم، ولی شما که میخوای از فری نود استفاده کنید خب استفاده کنید. این کد هم اگه سنگینه، استفاده نکنید. من واقعا متوجه این نوع گزارش مشکل نمیشم. اگه خطایی وجود داره خطا رو همراه مستندات و اسکرین شان ارسال کنید که بررسی کنم.
