### ISSUE TITLE
Uncaught (in response) Error: Worker exceeded CPU time limit. Error: Worker exceeded CPU time limit.

### ISSUE THREAD

**Issue by Makankn** [vfarid/v2ray-worker-sub#17]
بعد از Send کردن آیپی همچین اروری میده کنسول، باید چیکار کرد؟

**Comment by vfarid** [comment]
روی پنل ورکر اجراش نکنید. کد رو که دپلوی کردید، لینک ورکر رو با بروزر باز کنید.
