### ISSUE TITLE
مشکل با متغیر fplist

### ISSUE THREAD

**Issue by ahmad24shargh** [vfarid/v2ray-worker-sub#20]
سلام
به سهم خودم از زحمات شما برای نوشتن این کد تشکر میکتم.
ار کلاینت Nekobox اندروید استفاده میکتم.به تجربه متوجه شدم که متغیر uTLS fingerprint برای تست کانکشن و موفقیت اتصال خیلی مهمه.
تو کد شما به صورت رندوم از آرایه fplist این متغیر مقداردهی میشه.ولی برای من فقط یکی از این گزینه ها جواب میده.
تقاضا دارم یه ثابت به ابتدای کد اضافه کنید تا اگر کسی خواست بتونه به صورت صریح این متغیر رو مقداردهی کنه.

**Comment by ahmad24shargh** [comment]
/*
CONST_FPLIST can be initialized with one of the following string values:
"chrome"
"firefox"
"safari"
"edge"
"ios"
"android"
"random"
or
"none" for random initialize
*/
var CONST_FPLIST = "none";
.
.
.
.
if (fpList.includes(CONST_FPLIST)) {
	conf.fp = CONST_FPLIST;
	}
	else {
	conf.fp = fpList[Math.           floor(Math.random() * fpList.length)];
}

**Comment by vfarid** [comment]
این امکان به نسخه‌ی ۱.۷ اضافه شد
