### ISSUE TITLE
نبود   myConfigs

### ISSUE THREAD

**Issue by roohino** [vfarid/v2ray-worker-sub#22]
سلام
در بخش readme گفته شده برای وارد کردن کانفیگ های شخصی از const myConfigs: استفاده کنیم ولی این بخش اصلا در کد وجود نداره.
این احتمال را هم بدید شاید کسی نخواست از کانفیگ رایگان بقیه استفاده کنه و بخواهد از سرور شخصیش کانفیگ بگیره

**Comment by vfarid** [comment]
توی این نسخه امکان استفاده از کانفیگ شخصی حذف شده. برای کانفیگ شخصی نیاز به این پیچیدگی نیست.
