### ISSUE TITLE
Failed to run Core

### ISSUE THREAD

**Issue by SalarAbapour** [vfarid/v2ray-worker-sub#27]
سلام و تشکر 
در برنامه v2ray لب تاب و v2rayng اندروید، گروه آپدیت میشه و کانفیگ ها وارد میشن اما وقتی real delay تست می گیرم:
در اندروید همه کانفیگ ها -1 هستند و کار نمی کنند.
در ب تاب خطای زیر:
Xray 1.8.0 (Xray, Penetrates Everything.) Custom (go1.20.2 windows/amd64)
A unified platform for anti-censorship.
[Info] infra/conf/serial: Reading config: stdin:
Failed to start: main: failed to load config files: [stdin:] > infra/conf: Failed to build TLS config. > infra/conf: unknown fingerprint: ios_13
Cannot mix synchronous and asynchronous operation on process stream.
Failed to run Core, please see the log

**Comment by SalarAbapour** [comment]
با تنظیم 
?fp=chrome
حل شد. خیلی ممنون. عالییه

**Comment by hadisedaghati69** [comment]
اگر میش هتوضیح کامل بدین من نمیدونم چیکار کنم

**Comment by 500006** [comment]
سلام من مشکل failed to run core please see the log را حل کردم گزینه User Agent را تنظیم کنید اگر200 تا است 200 بذارید مشکل حل میشه

**Comment by Racoder-RA** [comment]
من هنوز این مشکل رو دارم، چجوری باید رفعش کنم؟


> سلام و تشکر در برنامه v2ray لب تاب و v2rayng اندروید، گروه آپدیت میشه و کانفیگ ها وارد میشن اما وقتی real delay تست می گیرم: در اندروید همه کانفیگ ها -1 هستند و کار نمی کنند. در ب تاب خطای زیر: Xray 1.8.0 (Xray, Penetrates Everything.) Custom (go1.20.2 windows/amd64) A unified platform for anti-censorship. [Info] infra/conf/serial: Reading config: stdin: Failed to start: main: failed to load config files: [stdin:] > infra/conf: Failed to build TLS config. > infra/conf: unknown fingerprint: ios_13 Cannot mix synchronous and asynchronous operation on process stream. Failed to run Core, please see the log

**Comment by vfarid** [comment]
این مشکل در نسخه ۱.۸ رفع شده ولی ورکر جدید که تو کتابخانه v2ray-worker نوشتم الان راه حل بهتریه.

**Comment by 123jhjh** [comment]
میشه راهنمایی کنید با جزییات منم همین مشکل رو دارم

> سلام و تشکر در برنامه v2ray لب تاب و v2rayng اندروید، گروه آپدیت میشه و کانفیگ ها وارد میشن اما وقتی real delay تست می گیرم: در اندروید همه کانفیگ ها -1 هستند و کار نمی کنند. در ب تاب خطای زیر: Xray 1.8.0 (Xray, Penetrates Everything.) Custom (go1.20.2 windows/amd64) A unified platform for anti-censorship. [Info] infra/conf/serial: Reading config: stdin: Failed to start: main: failed to load config files: [stdin:] > infra/conf: Failed to build TLS config. > infra/conf: unknown fingerprint: ios_13 Cannot mix synchronous and asynchronous operation on process stream. Failed to run Core, please see the log

**Comment by Arisp5** [comment]
> میشه راهنمایی کنید با جزییات منم همین مشکل رو دارم
> 
> > سلام و تشکر در برنامه v2ray لب تاب و v2rayng اندروید، گروه آپدیت میشه و کانفیگ ها وارد میشن اما وقتی real delay تست می گیرم: در اندروید همه کانفیگ ها -1 هستند و کار نمی کنند. در ب تاب خطای زیر: Xray 1.8.0 (Xray, Penetrates Everything.) Custom (go1.20.2 windows/amd64) A unified platform for anti-censorship. [Info] infra/conf/serial: Reading config: stdin: Failed to start: main: failed to load config files: [stdin:] > infra/conf: Failed to build TLS config. > infra/conf: unknown fingerprint: ios_13 Cannot mix synchronous and asynchronous operation on process stream. Failed to run Core, please see the log

قسمت سیتینگ default TLS fingerprint بزار روی chrome
