### ISSUE TITLE
Surfboard 

### ISSUE THREAD

**Issue by it3aeed71** [vfarid/v2ray-worker-sub#3]
سلام نمیشه کاری کرد که رو کلاینت surfboard کار کنه یا بشه هر کس با هر کلاینت که داره کد و تعغییر بده؟

**Comment by vfarid** [comment]
نمونه لینک sub برای surfborad ارسال کنید تا بررسی کنم.

**Comment by it3aeed71** [comment]
> نمونه لینک sub برای surfborad ارسال کنید تا بررسی کنم.

https://tt.vg/iwZQm
یه نمونه ولی پروتکل Vmess,ss, trojan روش کار می‌کنه و همچنین doh میتونی روش ست کنی
