### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by developer861** [vfarid/v2ray-worker-sub#35]
سلام وحید جان یه چنتا ایده داشتم واسه کد ورکر یکی اینکه به ورکر قابلیت تغییر پورت همه کانفیگارو اضافه کنی تا نیازی نباشه دستی برای gfw knocker پورتو عوض کنیم
یکی دیگه اینکه کانفگای شخصیم به نسخه آخر اضافه کنی بازم دمت گرم

**Comment by vfarid** [comment]
سلام. گزینه‌ی اول رو متوجه نشدم ولی گزینه‌ی دوم به نسخه‌ی ۲ که در کتابخانه‌ی v2ray-worker نوشتم اضافه شده. در مورد اولی اگه نیاز بود با توضیح کافی روی اون کتابخانه بفرستید. متشکرم
