### ISSUE TITLE
Add the ability to change ports in the appendix

### ISSUE THREAD

**Issue by philip-johnson45** [vfarid/v2ray-worker-sub#36]
سلام، وقت بخیر و خسته نباشید

پیشنهادی که دارم این هست که از کاربر بتواند در appendix بعد از uri وورکر، پورت دلخواه وارد کنه

تنها استفاده ای هم که دارد، این هست که افرادی که از اسکریپت GFW-Knocker و وورکر استفاده می‌کنند، بتوانند تست تاخیر بگیرند و سرور با تاخیر کمتر استفاده شود.
تشکر از شما و تلاشتان

**Comment by vfarid** [comment]
سلام و تشکر
من متوجه نشدم این چیه چون پورت کانفیگ رو که نباید عوض کرد دیگه کار نمیکنه. اگه نکته‌ای هست که من بهش توجه نکردم لطفا روی کتابخانه‌ی جدید v2ray-worker با توضیح کافی ارسال کنید. متشکرم.
