### ISSUE TITLE
با سلام و خسته نباشید
متاسفانه اون ساب ورکرهایی که توی تلگرام اعلام کردین همشون از کار افتادن یا شدیدا پهنای باندشون کم شده حالا یا از طرف کلودفلر یا از طرف زیرساخت.
یک محبت کنید، یک آموزش مناسب به ترتیب مرحله برای ساخت وورکر و ساب وورکر توی کانال بفرمایید.
فقط میتونم دامنه بخرم ولی چندین بار طبق یک سری آموزشها که جلو رفتم نتونستم ساب وورکر راه اندازی کنم.
مرسی ممنون

### ISSUE THREAD

**Issue by amir385276** [vfarid/v2ray-worker-sub#38]

**Comment by amir385276** [comment]
با سلام و خسته نباشیدمتاسفانه اون ساب ورکرهایی که توی تلگرام اعلام کردین همشون از کار افتادن یا شدیدا پهنای باندشون کم شده حالا یا از طرف کلودفلر یا از طرف زیرساخت.یک محبت کنید، یک آموزش مناسب به ترتیب مرحله برای ساخت وورکر و ساب وورکر توی کانال بفرمایید.فقط میتونم دامنه بخرم ولی چندین بار طبق یک سری آموزشها که جلو رفتم نتونستم ساب وورکر راه اندازی کنم.مرسی ممنون

**Comment by amir385276** [comment]
سرعت خيلي پائين اومده

**Comment by vfarid** [comment]
الان میتونید از کد جدید در کتابخانه v2ray-worker استفاده کنید.
