### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by arsaces7** [vfarid/v2ray-worker-sub#7]
سلام وقت بخیر
من می‌خوام که ورکر فقط ای پی های تمیز رو‌ به کانفیگ شخصیم اضافه کنه و ادرس request host رو تغییر نده ، الان به خوبی ای پی تمیز رو اضافه میکنه اما ادرس رو هم به دامین خود ورکر تغییر میده و ریکوست اضافی و محدودیت وورکر و غیره
امکانش هست فقط ای پی به کانفیگ اضافه بشه و بقیه کانفیگ بدون تغییر بمونه ؟

**Comment by vfarid** [comment]
بله میشه باید فورک کنید و اصلاح کنید. برای کاربردی که من نوشتم این کاری که خواستید نیاز نیست. حدس میزنم برای سرور شخصی میخواد. فرصت کنم تو کتابخانه ی جدا مینویسمش
